
model:
  name: "transformer"
  d_model: 64
  num_layers: 2
  num_heads: 4 
  max_len: 96
  positional_encoding: "sinusoidal"
  learnable_pos_encoding: false
  d_ff: 256  
  dropout: 0.2
  regression_head:
    output_dim: 1
    pooling: "mean"

data:
  input_data_path: "data/experiments/"

training:
  batch_size: 16
  num_workers: 0
  shuffle: true
  num_epochs: 100
  early_stopping_patience: 15
  optimiser: "adamw"
  learning_rate: 0.0001
  weight_decay: 0.001
  loss_function: "HuberLoss"
  scheduler:
    use_scheduler: true
    warmup_epochs: 3
    type: "ReduceLROnPlateau"
    patience: 7
    factor: 0.5
    mode: "min"
  gradient_clipping:
    use_clipping: true
    max_norm: 1.0

logging:
  log_interval: 10
  save_model: true
  save_best_model: true
  save_final_model: false